
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-16
owner: ucsb-cs156-s26
repo_name: team02-s26-16
pull_requests: [{"author":{"id":"U_kgDOCVIPTg","is_bot":false,"login":"sharanya444","name":"sharanya gehlot"},"headRefName":"sharanya444-Articles-form","number":68,"title":"Add ArticlesForm component, tests, and stories","url":"https://github.com/ucsb-cs156-s26/team02-s26-16/pull/68"},{"author":{"id":"MDQ6VXNlcjY4Mjk4MzE1","is_bot":false,"login":"JackLiu8","name":""},"headRefName":"Jack-MenuItemFixtures","number":66,"title":"Add UCSBDiningCommonsMenuItem fixtures","url":"https://github.com/ucsb-cs156-s26/team02-s26-16/pull/66"}]
