
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-16
owner: ucsb-cs156-s26
repo_name: team02-s26-16
pull_requests: [{"author":{"id":"U_kgDOCVIPTg","is_bot":false,"login":"sharanya444","name":"sharanya gehlot"},"headRefName":"sharanya444-Articles-index-page","number":81,"title":"Add ArticlesEditPage with tests and stories","url":"https://github.com/ucsb-cs156-s26/team02-s26-16/pull/81"},{"author":{"id":"U_kgDOCu1aKQ","is_bot":false,"login":"RohilJainUCSB","name":""},"headRefName":"rj-helprequest-createfixtures","number":80,"title":"RJ - Added helpRequestFixtures","url":"https://github.com/ucsb-cs156-s26/team02-s26-16/pull/80"},{"author":{"id":"U_kgDOCv6zKw","is_bot":false,"login":"JohnDSylvester","name":"John Sylvester"},"headRefName":"JS-MenuItemReview-Fixtures","number":79,"title":"JS-added fixtures for MenuItemReview","url":"https://github.com/ucsb-cs156-s26/team02-s26-16/pull/79"},{"author":{"id":"MDQ6VXNlcjY4Mjk4MzE1","is_bot":false,"login":"JackLiu8","name":""},"headRefName":"Jack-MenuItemForm","number":75,"title":"Add UCSBDiningCommonsMenuItem form, tests, and stories","url":"https://github.com/ucsb-cs156-s26/team02-s26-16/pull/75"},{"author":{"id":"U_kgDOCuipXA","is_bot":false,"login":"nikitahuynh","name":""},"headRefName":"nh-UCSBOrganization-form-component","number":74,"title":"Nh ucsb organization form component","url":"https://github.com/ucsb-cs156-s26/team02-s26-16/pull/74"}]
