
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-16
owner: ucsb-cs156-s26
repo_name: team02-s26-16
pull_requests: [{"author":{"id":"U_kgDOCv6zKw","is_bot":false,"login":"JohnDSylvester","name":"John Sylvester"},"headRefName":"JS-MenuItemReview-CreatePage","number":113,"title":"JS - menu item review create page","url":"https://github.com/ucsb-cs156-s26/team02-s26-16/pull/113"},{"author":{"id":"U_kgDOCv6zKw","is_bot":false,"login":"JohnDSylvester","name":"John Sylvester"},"headRefName":"JS-MenuItemReview-Placeholders","number":109,"title":"JS-Added MenuItemReviews Pages to the NavBar","url":"https://github.com/ucsb-cs156-s26/team02-s26-16/pull/109"}]
